const ragService = require('./ragService');

const generateMeetingLink = () => {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 8);
  const meetingRoom = `kanoon-${timestamp}-${random}`;
  return `https://meet.jit.si/${meetingRoom}`;
};

const chatWithAI = async (userMessage, conversationHistory = [], recommendLawyers = null, language = 'english', userId = null) => {
  const result = await ragService.processMessage(userMessage, userId, recommendLawyers, language, conversationHistory);
  return result;
};

const generateConversationPDF = (messages, userName) => {
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  let content = `
╔══════════════════════════════════════════════════════════════╗
║                    KANOONSATHI LEGAL CONSULTATION               ║
║                    AI Legal Assistant Transcript               ║
╚══════════════════════════════════════════════════════════════╝

Date: ${date}
User: ${userName || 'Anonymous'}
Platform: KanoonSathi - Nepal's Legal Platform

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                              CHAT HISTORY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

  messages.forEach((msg, i) => {
    const time = new Date(msg.timestamp).toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit'
    });

    if (msg.role === 'user') {
      content += `\n[${time}] YOU:\n${msg.message}\n`;
    } else {
      content += `\n[${time}] KANOONSATHI AI:\n${msg.message}\n`;
    }
    content += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
  });

  content += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

                         IMPORTANT NOTICE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This conversation is for informational purposes only and does
not constitute legal advice. The information provided is based
on Nepali law and regulations as of the date of this transcript.

For specific legal advice, please consult a qualified lawyer.

To book a consultation:
1. Visit our website: kanoonsathi.np
2. Go to Lawyers section
3. Filter by specialization
4. Book appointment

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by KanoonSathi AI Legal Assistant
(c) 2024 KanoonSathi - Your Trusted Legal Partner in Nepal

`;

  return content;
};

module.exports = {
  chatWithAI,
  generateMeetingLink,
  generateConversationPDF,
  ragService
};
